// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXDl9JUjYNp5QFBe0K8VlemfPb_z3cbng',
    appId: '1:793194430829:web:df30aa44dbd16f31311a64',
    messagingSenderId: '793194430829',
    projectId: 'raising-6ef34',
    authDomain: 'raising-6ef34.firebaseapp.com',
    storageBucket: 'raising-6ef34.firebasestorage.app',
    measurementId: 'G-CEKE8LL684',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDASNlUbwbH6YnJxifxtmGhfFmxvTacYk',
    appId: '1:793194430829:android:f8cc4d5003126f8b311a64',
    messagingSenderId: '793194430829',
    projectId: 'raising-6ef34',
    storageBucket: 'raising-6ef34.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcpGL5FRrUHb2oMMRC8K4IF7urJAy43HE',
    appId: '1:793194430829:ios:5871b7f825f43d67311a64',
    messagingSenderId: '793194430829',
    projectId: 'raising-6ef34',
    storageBucket: 'raising-6ef34.firebasestorage.app',
    iosBundleId: 'com.example.raisingIndia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcpGL5FRrUHb2oMMRC8K4IF7urJAy43HE',
    appId: '1:793194430829:ios:5871b7f825f43d67311a64',
    messagingSenderId: '793194430829',
    projectId: 'raising-6ef34',
    storageBucket: 'raising-6ef34.firebasestorage.app',
    iosBundleId: 'com.example.raisingIndia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXDl9JUjYNp5QFBe0K8VlemfPb_z3cbng',
    appId: '1:793194430829:web:0c8a6c41f9737395311a64',
    messagingSenderId: '793194430829',
    projectId: 'raising-6ef34',
    authDomain: 'raising-6ef34.firebaseapp.com',
    storageBucket: 'raising-6ef34.firebasestorage.app',
    measurementId: 'G-1L1TKJ29SV',
  );
}
