// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1z_u4WeTW3n_KglPSkPuBD_Iz5oLQHpU',
    appId: '1:657027117935:web:424ac6c6c974ab51042e9a',
    messagingSenderId: '657027117935',
    projectId: 'rising-mart',
    authDomain: 'rising-mart.firebaseapp.com',
    storageBucket: 'rising-mart.firebasestorage.app',
    measurementId: 'G-1RY815WTKZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0A-99S3VEg8bRrnQNmuo_YEUBMuUZT_0',
    appId: '1:657027117935:android:c8475fc85c1adaa8042e9a',
    messagingSenderId: '657027117935',
    projectId: 'rising-mart',
    storageBucket: 'rising-mart.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD79XTtS7NgRIQ1gEqSRYprnLl6-PV6gQA',
    appId: '1:657027117935:ios:8979539acd332a81042e9a',
    messagingSenderId: '657027117935',
    projectId: 'rising-mart',
    storageBucket: 'rising-mart.firebasestorage.app',
    iosBundleId: 'com.example.raisingIndia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD79XTtS7NgRIQ1gEqSRYprnLl6-PV6gQA',
    appId: '1:657027117935:ios:8979539acd332a81042e9a',
    messagingSenderId: '657027117935',
    projectId: 'rising-mart',
    storageBucket: 'rising-mart.firebasestorage.app',
    iosBundleId: 'com.example.raisingIndia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1z_u4WeTW3n_KglPSkPuBD_Iz5oLQHpU',
    appId: '1:657027117935:web:b1297829317db18c042e9a',
    messagingSenderId: '657027117935',
    projectId: 'rising-mart',
    authDomain: 'rising-mart.firebaseapp.com',
    storageBucket: 'rising-mart.firebasestorage.app',
    measurementId: 'G-8TC6252VT2',
  );
}
